### ISSUE TITLE
how to convert png to xml

### ISSUE THREAD

**Issue by kimtaehyeong** [SarderLab/H-AI-L#1]
Hello. I am very interested in your results. 

First, I have a question.
I have my pathology png image, and I want to convert it to an xml format that fits the result.
How do I convert it?

Thank you for your good research.

**Comment by brendonlutnick** [comment]
This functionality is built into the IterativePredict.py script.  Check line 632 "def crop_suey" this takes a integer .png mask and converts it to xml file.
